version: '3.7'

services:
  test:
    build:
      context: .
    image: prefapp-core:latest
    working_dir: /home/app
    entrypoint:
    - bash
    - -c
    command:
    - "python -m unittest discover test/"
    volumes:
    - '.:/home/app'
